### ISSUE TITLE
Can you please upload the complete Vivado Project files so that we can import it and work on it 

### ISSUE THREAD

**Issue by developeralgo8888** [rkharris12/fpga_bitcoin_miner#4]
Please upload the Vivado Project file for easy import so that we can work with sources to add other algorithms quickly

**Comment by rkharris12** [comment]
I added a TCL script which should allow you to regenerate the Vivado project.  Try pulling the latest changes and follow the new instructions in the REAMDE

**Comment by developeralgo8888** [comment]
thanks, Have tried other coins for testing ?

**Comment by rkharris12** [comment]
Not yet
