### ISSUE TITLE
To Generate bitstreams (binary) file if i change the digesters number to 64

### ISSUE THREAD

**Issue by developeralgo8888** [rkharris12/fpga_bitcoin_miner#6]
in Vivado 2019.1 ,  Do i just  modify the value from 1 to 0  and then 

1. Run the Synthesis
2. Run the Implementation
3. Generate the Bistreams 

or is there a different way to do it faster?

**Comment by rkharris12** [comment]
Yes, that is correct.  No faster way.  But I could not get 64 digesters to place-and-route successfully on the Pynq Z2 because the design was too large
