### ISSUE TITLE
Call api but not working

### ISSUE THREAD

**Issue by marklei951130** [rkharris12/fpga_bitcoin_miner#8]
Hi rkharris12, thank you for sharing out this cool project. 
I try to implement this project, and input the command on pynq-z2(with image v2.5) like: 
root@pynq:/home/xilinx# python3 fpgaminer.py -o stratum+tcp://36rNgDDr5XGZYJrawRc1m1FqZP21d6oBBp@sha256.usa-west.nicehash.com:3334 -u xilinx -p xilinx -i auto
[2022-01-21 04:14:00] [DEBUG] Using sha256d library 'hashlib'
[2022-01-21 04:14:00] [INFO] Starting server on sha256.usa-west.nicehash.com:3334
[2022-01-21 04:14:00] JSON-RPC Server < {"id": 1, "method": "mining.subscribe", "params": ["FPGAMiner/0.1"]}

1. (-o) -> I have tried Slushpool too, like "stratum+tcp://stratum.slushpool.com:3333", and nice hash like above, either not worked at all.
2. (-u -p) -> I have tried Slushpool username and pwd, And also I have tried the nicehash ASIC device username and pwd of nicehash. The -u -p of command above is my co-worker tell me to use the uname and pwd of z2.
3. I put the folder(overlays) , fpgaminer.py and sha256d_fpga_sim.py under /home/xilinx/.

So, is it possible to ask you for the api implement detail? What pool url format I should use? And what is the correspond uname and password? Thank you again.

**Comment by rkharris12** [comment]
Hi, I don't see anything wrong with the slushpool url you used, and I haven't tried nicehash so I'm not sure about that.  Your Slushpool username and password should go in the -u and -p arguments.  Your directory structure seems fine.  Could you give more detail on the error messages you get?

**Comment by marklei951130** [comment]
Hi, after brought it home and tested on my PC, it worked. I found out the intranet of our office blocked something to let us failed to connect with the pool.

Thank you for the comment !
